# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: alex <marvin@42.fr>                        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/07/15 19:18:25 by alex              #+#    #+#              #
#    Updated: 2020/07/15 19:51:09 by alex             ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME	:= do_op
INC_DIR	:= includes/
SRCS	:= srcs/chosen_func.c srcs/do_op.c srcs/ft_atoi.c srcs/val_error.c \
		srcs/ft_subs.c srcs/ft_add.c srcs/ft_div.c srcs/ft_mod.c \
		srcs/ft_multi.c srcs/ft_putnbr.c srcs/ft_putchar.c srcs/main.c \
		srcs/ft_putstr.c
OBJ	:= $(SRCS:.c=.o)
